name: check PR (node_backup)

on:
  pull_request:
    paths:
      - roles/node_backup/**
      - .github/**
  push:
    paths:
      - roles/node_backup/**
      - .github/**
    branches:
      - '!main'
      - '**'

jobs:
  run-molecule-tests:
    strategy:
      fail-fast: false
      matrix:
        molecule-driver: [docker]
    uses: ./.github/workflows/reusable-molecule.yml
    with:
      role-name: node
      molecule-driver: ${{ matrix.molecule-driver }}