name: check PR (nginx_exporter)

on:
  pull_request:
    paths:
      - roles/nginx_exporter/**
      - .github/**
  push:
    paths:
      - roles/nginx_exporter/**
      - .github/**
    branches:
      - '!main'
      - '**'

jobs:
  run-molecule-tests:
    strategy:
      fail-fast: false
      matrix:
        molecule-driver: [docker]
    uses: ./.github/workflows/reusable-molecule.yml
    with:
      role-name: nginx_exporter
      molecule-driver: ${{ matrix.molecule-driver }}
